spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: mysecretpassword
    url: jdbc:postgresql://0.0.0.0:5432/postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: false
      path: /console
